# Site settings
title: Lee
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.leesnotes.org" # the base hostname & protocol for your site

author:
  fullname: Tian Lee
  googleplus: https://www.google.com/+TianLee82
  github: fatdali
  twitter: fatdali
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown